export default {
  connectionStr: 'http://localhost:3000',
  successMsg: 'Success',
  wrongCardNumberMsg: 'Wrong card number!',
  wrongCardExpiresMsg: 'Wrong card expires!',
  wrongCardCvvMsg: 'Wrong card CVV!',
  wrongEMailMsg: 'Wrong E-Mail!',
  mismatchedEMailMsg: 'No such user!',
  wrongPasswordMsg: 'Wrong password!',
  wrongCurrPasswordMsg: 'Wrong current password!',
  shortPasswordMsg: 'Password cannot be less then 5 characters!',
  mismatchedPasswordMsg: 'Passwords do not match!',
  wrongLoginMsg: 'Wrong login!',
  wrongAgeMsg: 'Wrong age!',
  userExistsMsg: 'Such user already exists!',
  nonAuthMsg: 'You need to log in/ register',
  wrongNameMsg: 'Wrong name!',
  wrongSurnameMsg: 'Wrong surname!',
  wrongAddressMsg: 'Wrong delivery address!',
  wrongPhoneMsg: 'Wrong phone number!',
  wrongDayMsg: 'Wrong delivery day!',
}
